# Association Mapping

library(Matrix);library(dplyr);library(tidyr);library(readr);library(ggplot2);library(scales);library(arules);library(arulesViz);library(readr)

# DXID data (From Novant)
# 100,000 observations
or_id_dxid_strict <- read_csv('C:/Users/dwilimits/Google Drive/Association mapping/order_id_dxid_novant.csv')

# 10 MIL observations
or_id_dxid_strict <- read_csv('C:/Users/dwilimits/Google Drive/Association mapping/novant_icd_data_fptest.csv')
colnames(or_id_dxid_strict) <- c("order_id", "DXID")

# 100 MIL observations
or_id_dxid_strict <- read_csv('C:/Users/dwilimits/Google Drive/Association mapping/novant_icd_test_data_big.csv')
colnames(or_id_dxid_strict) <- c("order_id", "DXID")

# DXID descriptions
dxid_desc_table <- read_csv('C:/Users/dwilimits/Google Drive/Association mapping/dxid_desc_table.csv')
colnames(dxid_desc_table) <- c(
  'DXID',
  'DXID_DESC56',
  'DXID_DESC100',
  'DXID_STATUS',
  'FDBDX',
  'DXID_DISEASE_DURATION_CD'
)

# map order ID and DXID to conecutive integers to keep the matrix size down
or_id_dxid_2 <- or_id_dxid_strict %>%
  left_join(or_id_dxid_strict %>%
              select(order_id) %>%
              distinct() %>%
              mutate(ord_id_2 = rank(as.numeric(order_id),ties.method = 'min'))) %>%
  left_join(or_id_dxid_strict %>%
              select(DXID) %>%
              distinct() %>%
              mutate(DXID_2 = rank(as.numeric(DXID),ties.method = 'min')))

# create keys so we can get back to original DXIDs
ord_key <- or_id_dxid_2 %>%
  select(order_id,ord_id_2) %>%
  distinct()

dxid_key <- or_id_dxid_2 %>%
  select(DXID,DXID_2) %>%
  distinct()

# create the matrix with orders as one dimension and DXIDs as the other
# Start by selecting the unique combinations of the keys to ord_id and dxid
or_id_dxid_3 <- or_id_dxid_2 %>%
  select(ord_id_2,DXID_2)

# Pivot to a sparse "Triplet" matrix
m <- new("ngTMatrix", 
         i = as.integer(or_id_dxid_3$DXID_2)-1L, 
         j = as.integer(or_id_dxid_3$ord_id_2)-1L, 
         Dim = as.integer(c(length(unique(or_id_dxid_3$DXID_2)), length(unique((or_id_dxid_3$ord_id_2))))))

# Convert to a column-oriented matrix
m <- as(m, "ngCMatrix")

# Convert to transactions
tr <- as(m, "transactions")
inspect(tr)
summary(tr)

# Apriori Algorithm
# run time = 44s
start.time <- Sys.time()
rules.all <- apriori(tr, 
                     parameter = list(supp = 0.01, conf = 0.75, minlen = 2, maxlen=2))
end.time <- Sys.time()
time.taken <- end.time - start.time
time.taken

# reading the rules into a data frame
ap_rules_df <- data.frame(
  lhs = labels(lhs(rules.all)),
  rhs = labels(rhs(rules.all)), 
  rules.all@quality)

plot(rules.all[1:101],method="graph",interactive = T)
plot(rules.all[101:200],method="graph",interactive = T)
plot(rules.all[601:900],method="graph",interactive = T)
plot(rules.all,method="graph",interactive = T)

# FP Growth
# converting transactions data to usable form
tr_df <- as(tr, "data.frame")
tr_df <- tr_df %>%
  mutate(items = gsub('\\{', "", items),
         items = gsub('\\}', "", items))

itemsets <- tr_df$items
write.table(itemsets, "itemsets.txt", sep = ",", quote = FALSE, row.names = FALSE, col.names = FALSE)

# set the mining parameters
minlen <- 2                     # Min length of itemset = 2 (excluding rules with empty set)
maxlen <- 2                     # Max length of itemset = 2
conf <- 75                      # Minimum confidence of a rule = 75%
supp <- 1                       # Minimum support = 1%

# build the command to read in transactions, run fp growth, and write association rules to a text file
# runs windows executable downloaded from http://www.borgelt.net/fpgrowth.html
# documentation on fpgrowth implementation at http://www.borgelt.net//doc/fpgrowth/fpgrowth.html#top
cmd <- paste("fpgrowth",
             paste0("-m", minlen),
             paste0("-n", maxlen),
             paste0("-s", supp),
             paste0("-c", conf),
             "-tr", "-I,", "-v,%X,%C,%l",
             "itemsets.txt", "itemsets_output.out", sep=" ")

# execute the command
# run time - 10s
start.time <- Sys.time()
system(cmd)
end.time <- Sys.time()
time.taken <- end.time - start.time
time.taken

# read the association rules into a data frame
fprules_df <- read.delim("itemsets_output.out", header = FALSE, sep = ",")
colnames(fprules_df) <- c("lhs", "rhs", "support", "confidence", "lift")
tmp_rhs <- fprules_df$lhs
fprules_df$lhs <- fprules_df$rhs
fprules_df$rhs <- tmp_rhs

# investigating difference in rules between A Priori and FP Growth
ap_rules_df <- ap_rules_df %>%
  mutate(lhs = as.integer(gsub('[{]|[}]','',lhs)),
         rhs = as.integer(gsub('[{]|[}]','',rhs)))

# (every rule contained in A Priori is also in FP Growth)
common_rules_df <- ap_rules_df %>%
  inner_join(fprules_df, by = c("lhs", "rhs"))

# additional rules generated by FP Growth
fp_common_rules_df <- common_rules_df %>%
  select(lhs, rhs, support.y, confidence.y, lift.y)
colnames(fp_common_rules_df) <- c("lhs", "rhs", "support", "confidence", "lift")

x <- rbind(fprules_df, fp_common_rules_df)
fp_unique_rules <- x[! duplicated(x, fromLast=TRUE) & seq(nrow(x)) <= nrow(fprules_df), ]

# add back the real dxids
ap_rules_df_2 <- ap_rules_df %>%
  mutate(lhs = as.integer(gsub('[{]|[}]','',lhs)),
         rhs = as.integer(gsub('[{]|[}]','',rhs))) %>%
  inner_join(dxid_key, by = c('lhs'='DXID_2')) %>%
  inner_join(dxid_key, by = c('rhs'='DXID_2')) %>%
  rename(ASSOCIATED_DXID = DXID.y,
         DXID = DXID.x) %>%
  left_join(select(dxid_desc_table,DXID,DXID_DESC100)) %>%
  rename(antecedent_desc = DXID_DESC100) %>%
  left_join(select(dxid_desc_table,DXID,DXID_DESC100),by=c('ASSOCIATED_DXID' = 'DXID')) %>%
  rename(consequent_desc = DXID_DESC100)

# add back the real dxids
fp_rules_df_2 <- fprules_df %>%
  mutate(lhs = as.integer(lhs),
         rhs = as.integer(rhs)) %>%
  inner_join(dxid_key, by = c('lhs'='DXID_2')) %>%
  inner_join(dxid_key, by = c('rhs'='DXID_2')) %>%
  rename(ASSOCIATED_DXID = DXID.y,
         DXID = DXID.x) %>%
  left_join(select(dxid_desc_table,DXID,DXID_DESC100)) %>%
  rename(antecedent_desc = DXID_DESC100) %>%
  left_join(select(dxid_desc_table,DXID,DXID_DESC100),by=c('ASSOCIATED_DXID' = 'DXID')) %>%
  rename(consequent_desc = DXID_DESC100)

# write some functions to investigate your plots
# this one takes the input of the keys and returns DXIDs
check_assoc <- function(x, df){
  df %>% 
    mutate(side = ifelse(lhs == x,'Antecedent','Consquent')) %>%
    filter(rhs == x | lhs == x) %>%
    select(antecedent_desc,consequent_desc,side)
}

# this one takes the input of the DXIDs and returns DXIDs
check_assoc_dxid <- function(x, df){
  df %>% 
    mutate(side = ifelse(DXID == x,'Antecedent','Consquent')) %>%
    filter(DXID == x | ASSOCIATED_DXID == x) %>%
    select(antecedent_desc,consequent_desc,side)
}